name: Update Streak Chart

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  update-streak:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download Streak Image
        # Corrected the link below (removed "-action")
        uses: DenverCoder1/github-readme-streak-stats@v3
        with:
          github_username: ${{ github.repository_owner }}
          output_path: streak.svg
          theme: transparent
          hide_border: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add streak.svg
          git commit -m "Update streak chart" || exit 0
          git push
